language: php

dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

sudo: false

install: travis_retry composer install --prefer-source

script:
  - if [[ "`phpenv version-name`" != "7.1" ]]; then make ci; fi
  - composer test

after_success:
  - if [[ "`phpenv version-name`" != "7.1" ]]; then exit 0; fi
  - vendor/bin/phpunit --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
